services:
  pacs:
    container_name: pacs-lite-orthanc
    image: jodogne/orthanc-plugins:1.12.9
    ports:
      # - 127.0.0.1:8042:8042
      # - 127.0.0.1:4242:4242
      # - ${COMPOSE_PORT_HTTP:-8042}:8042
      # - ${COMPOSE_PORT_DCOM:-4242}:4242
      - 8042:8042
      - 4242:4242
    #   - 127.0.0.1:8042:8042
    #   - 127.0.0.1:4242:4242
    # expose:
    #   - "8042"
    #   - "4242"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
      - ./WorklistsDatabase:/var/tmp/WorklistsDatabase/
      - ./logo.png:/logo.png:ro
      - ./scripts:/usr/share/orthanc/scripts
    restart: always
    networks:
      - pacs-lite
      - rfproxy

  ohif_viewer:
    container_name: pacs-lite-ohif
    image: ohif/app:v3.11.0
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs-lite

networks:
  pacs-lite:
    driver: bridge
  rfproxy:
    external: true
