server {
  listen 80;

  client_max_body_size 800M;

  root /usr/share/nginx/html;

  gzip_static on;

  # OHIF PUBLIC ASSETS
  # /public-assets/*
  # -> /usr/share/nginx/html/*
  location ^~ /public-assets/ {
    rewrite ^/public-assets/(.*)$ /$1 break;
    try_files $uri =404;
  }

  # OHIF
  location / {
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /logo.png {
    root /usr/share/nginx/html;
  }

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
    root /usr/share/nginx/html;
  }

  # ORTHANC
  location /orthanc/ {
    proxy_pass http://pacs:8042;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    rewrite /orthanc(.*) $1 break;
  }
}

